// Real-world travel data for AI Mini Travel Planner

export const DESTINATION_COORDS: Record<string, { lat: number; lng: number }> = {
    "东京": { lat: 35.6762, lng: 139.6503 },
    "大阪": { lat: 34.6937, lng: 135.5023 },
    "京都": { lat: 35.0116, lng: 135.7681 },
    "首尔": { lat: 37.5665, lng: 126.9780 },
    "釜山": { lat: 35.1796, lng: 129.0756 },
    "济州岛": { lat: 33.4996, lng: 126.5312 },
    "北京": { lat: 39.9042, lng: 116.4074 },
    "上海": { lat: 31.2304, lng: 121.4737 },
    "广州": { lat: 23.1291, lng: 113.2644 },
    "深圳": { lat: 22.5431, lng: 114.0579 },
    "成都": { lat: 30.5728, lng: 104.0668 },
    "杭州": { lat: 30.2741, lng: 120.1551 },
    "西安": { lat: 34.3416, lng: 108.9398 },
    "曼谷": { lat: 13.7563, lng: 100.5018 },
    "新加坡": { lat: 1.3521, lng: 103.8198 },
    "巴黎": { lat: 48.8566, lng: 2.3522 },
    "伦敦": { lat: 51.5074, lng: -0.1278 },
    "纽约": { lat: 40.7128, lng: -74.0060 },
    "悉尼": { lat: -33.8688, lng: 151.2093 },
    "香港": { lat: 22.3193, lng: 114.1694 },
    "台北": { lat: 25.0330, lng: 121.5654 },
};

export interface Attraction {
    name: string;
    description: string;
    lat: number;
    lng: number;
    category: string;
    duration: string;
    cost: number;
    timeSlot: string;
}

export const ATTRACTIONS: Record<string, Attraction[]> = {
    "东京": [
        { name: "浅草寺", description: "东京最古老的寺庙，参观雷门、仲见世商店街，感受江户风情", lat: 35.7146, lng: 139.7967, category: "历史", duration: "1.5小时", cost: 0, timeSlot: "09:00" },
        { name: "秋叶原电器街", description: "全球知名的动漫和电子产品圣地，探索各种主题咖啡馆和电器店", lat: 35.6764, lng: 139.7639, category: "动漫", duration: "2小时", cost: 0, timeSlot: "10:30" },
        { name: "涩谷十字路口", description: "世界最繁忙的十字路口，打卡忠犬八公像，逛涩谷109", lat: 35.6586, lng: 139.7454, category: "摄影", duration: "1小时", cost: 0, timeSlot: "14:00" },
        { name: "新宿御苑", description: "东京最大的日式庭园之一，融合日式、法式和英式园林风格", lat: 35.6329, lng: 139.7153, category: "自然", duration: "2小时", cost: 500, timeSlot: "15:30" },
        { name: "东京塔", description: "东京标志性建筑，俯瞰东京全景，夜景尤为壮观", lat: 35.6586, lng: 139.7454, category: "夜景", duration: "1.5小时", cost: 1200, timeSlot: "19:00" },
        { name: "筑地市场", description: "东京最大的海鲜市场，品尝最新鲜的寿司和海鲜丼", lat: 35.6654, lng: 139.7707, category: "美食", duration: "2小时", cost: 3000, timeSlot: "08:00" },
        { name: "明治神宫", description: "东京最重要的神社，漫步在参天古木的林荫道上", lat: 35.6764, lng: 139.6993, category: "历史", duration: "1.5小时", cost: 0, timeSlot: "09:30" },
        { name: "表参道", description: "东京的时尚地标，汇集国际奢侈品牌和建筑设计精品", lat: 35.6654, lng: 139.7109, category: "购物", duration: "2小时", cost: 0, timeSlot: "14:00" },
    ],
    "大阪": [
        { name: "大阪城公园", description: "日本历史名城，天守阁内展示丰臣秀吉的历史文物", lat: 34.6873, lng: 135.5262, category: "历史", duration: "2小时", cost: 600, timeSlot: "09:00" },
        { name: "道顿堀", description: "大阪最繁华的美食街，招牌蟹道乐和格力高跑男是标志性打卡点", lat: 34.6687, lng: 135.5023, category: "美食", duration: "2小时", cost: 0, timeSlot: "11:30" },
        { name: "环球影城", description: "日本环球影城，拥有哈利波特、马里奥等主题园区", lat: 34.6713, lng: 135.4318, category: "摄影", duration: "6小时", cost: 9800, timeSlot: "14:00" },
        { name: "通天阁", description: "大阪的地标建筑，展望台可俯瞰整个大阪市景", lat: 34.6603, lng: 135.4992, category: "夜景", duration: "1小时", cost: 800, timeSlot: "19:00" },
        { name: "梅田蓝天大厦", description: "空中庭园展望台，欣赏大阪360度全景夜景", lat: 34.6937, lng: 135.5023, category: "夜景", duration: "1.5小时", cost: 1500, timeSlot: "20:00" },
        { name: "黑门市场", description: "大阪的厨房，品尝新鲜海鲜、河豚和当地小吃", lat: 34.6687, lng: 135.5023, category: "美食", duration: "1.5小时", cost: 2000, timeSlot: "10:00" },
    ],
    "首尔": [
        { name: "景福宫", description: "朝鲜王朝的正宫，穿韩服可免费入场，感受韩国传统文化", lat: 37.5796, lng: 126.9770, category: "历史", duration: "2小时", cost: 3000, timeSlot: "09:00" },
        { name: "北村韩屋村", description: "首尔最具传统特色的韩屋密集区，漫步在古色古香的巷弄中", lat: 37.5841, lng: 127.0020, category: "摄影", duration: "1.5小时", cost: 0, timeSlot: "11:00" },
        { name: "明洞购物街", description: "首尔最繁华的购物区，汇集韩国美妆、时尚和美食", lat: 37.5665, lng: 126.9780, category: "购物", duration: "2小时", cost: 0, timeSlot: "14:00" },
        { name: "弘大艺术街", description: "充满青春活力的艺术街区，街头表演和独立设计师店铺林立", lat: 37.5563, lng: 126.9236, category: "咖啡馆", duration: "2小时", cost: 0, timeSlot: "16:00" },
        { name: "N首尔塔", description: "首尔地标，挂满爱情锁，俯瞰首尔璀璨夜景", lat: 37.5512, lng: 126.9882, category: "夜景", duration: "1.5小时", cost: 12000, timeSlot: "19:00" },
        { name: "广藏市场", description: "首尔历史最悠久的传统市场，品尝活章鱼和绿豆煎饼", lat: 37.5700, lng: 126.9990, category: "美食", duration: "1.5小时", cost: 15000, timeSlot: "12:00" },
    ],
    "北京": [
        { name: "故宫博物院", description: "明清两代的皇家宫殿，世界最大的古代宫殿建筑群", lat: 39.9163, lng: 116.3972, category: "历史", duration: "3小时", cost: 60, timeSlot: "09:00" },
        { name: "天安门广场", description: "世界最大的城市广场，观看升旗仪式，参观人民英雄纪念碑", lat: 39.9042, lng: 116.4074, category: "历史", duration: "1小时", cost: 0, timeSlot: "08:00" },
        { name: "颐和园", description: "中国古典园林的巅峰之作，昆明湖和万寿山交相辉映", lat: 39.9930, lng: 116.3264, category: "自然", duration: "2.5小时", cost: 30, timeSlot: "14:00" },
        { name: "南锣鼓巷", description: "北京最古老的胡同区之一，感受老北京的生活气息", lat: 39.9493, lng: 116.3919, category: "美食", duration: "1.5小时", cost: 0, timeSlot: "16:30" },
        { name: "王府井步行街", description: "北京最著名的商业街，汇集各大品牌和老字号", lat: 39.9150, lng: 116.3979, category: "购物", duration: "2小时", cost: 0, timeSlot: "19:00" },
        { name: "长城（八达岭）", description: "世界七大奇迹之一，登长城感受雄伟壮观", lat: 40.3573, lng: 116.0137, category: "自然", duration: "4小时", cost: 45, timeSlot: "08:00" },
    ],
    "上海": [
        { name: "外滩", description: "上海的城市名片，欣赏万国建筑群和陆家嘴天际线", lat: 31.2304, lng: 121.4737, category: "摄影", duration: "1.5小时", cost: 0, timeSlot: "09:00" },
        { name: "陆家嘴金融中心", description: "登顶上海中心大厦或东方明珠，俯瞰上海全景", lat: 31.2354, lng: 121.5016, category: "夜景", duration: "2小时", cost: 180, timeSlot: "10:30" },
        { name: "豫园", description: "明代江南古典园林，体验老城隍庙的市井风情", lat: 31.2253, lng: 121.4684, category: "历史", duration: "1.5小时", cost: 40, timeSlot: "14:00" },
        { name: "新天地", description: "上海时尚地标，石库门建筑改造的国际化街区", lat: 31.1946, lng: 121.4390, category: "咖啡馆", duration: "1.5小时", cost: 0, timeSlot: "16:00" },
        { name: "南京路步行街", description: "中华第一商业街，从人民广场到外滩的购物天堂", lat: 31.2304, lng: 121.4737, category: "购物", duration: "2小时", cost: 0, timeSlot: "19:00" },
        { name: "迪士尼乐园", description: "上海迪士尼度假区，体验奇幻童话城堡和创极速光轮", lat: 31.1430, lng: 121.6570, category: "摄影", duration: "8小时", cost: 475, timeSlot: "08:00" },
    ],
    "广州": [
        { name: "广州塔", description: "广州地标建筑，登塔俯瞰珠江新城全景，体验摩天轮", lat: 23.1291, lng: 113.2644, category: "夜景", duration: "2小时", cost: 150, timeSlot: "09:00" },
        { name: "珠江夜游", description: "乘坐游船欣赏珠江两岸的璀璨夜景", lat: 23.1198, lng: 113.2588, category: "夜景", duration: "1.5小时", cost: 98, timeSlot: "19:00" },
        { name: "沙面岛", description: "欧陆风情建筑群，广州的露天建筑博物馆", lat: 23.1328, lng: 113.2665, category: "摄影", duration: "1.5小时", cost: 0, timeSlot: "10:00" },
        { name: "北京路步行街", description: "广州最繁华的商业街，千年古道遗址就在脚下", lat: 23.1378, lng: 113.2597, category: "购物", duration: "2小时", cost: 0, timeSlot: "14:00" },
        { name: "长隆野生动物世界", description: "亚洲最大的野生动物主题公园，近距离接触珍稀动物", lat: 23.1088, lng: 113.3268, category: "自然", duration: "4小时", cost: 300, timeSlot: "09:30" },
        { name: "上下九步行街", description: "广州传统骑楼商业街，品尝地道广州小吃", lat: 23.1328, lng: 113.2665, category: "美食", duration: "2小时", cost: 0, timeSlot: "16:00" },
    ],
    "成都": [
        { name: "大熊猫繁育研究基地", description: "近距离观看国宝大熊猫，看可爱的熊猫宝宝玩耍", lat: 30.7117, lng: 104.0451, category: "自然", duration: "3小时", cost: 55, timeSlot: "08:00" },
        { name: "宽窄巷子", description: "成都最具代表性的历史文化街区，体验老成都生活", lat: 30.6635, lng: 104.0725, category: "美食", duration: "2小时", cost: 0, timeSlot: "11:00" },
        { name: "锦里古街", description: "三国文化主题街区，品尝成都特色小吃和变脸表演", lat: 30.6598, lng: 104.0478, category: "美食", duration: "1.5小时", cost: 0, timeSlot: "14:00" },
        { name: "武侯祠", description: "纪念诸葛亮的祠庙，三国文化的重要遗址", lat: 30.6700, lng: 104.0630, category: "历史", duration: "1.5小时", cost: 60, timeSlot: "15:30" },
        { name: "春熙路", description: "成都最繁华的商业街，IFS熊猫爬墙是网红打卡点", lat: 30.6500, lng: 104.0800, category: "购物", duration: "2小时", cost: 0, timeSlot: "19:00" },
        { name: "人民公园", description: "体验成都慢生活，喝盖碗茶、掏耳朵、看川剧", lat: 30.6635, lng: 104.0725, category: "咖啡馆", duration: "2小时", cost: 0, timeSlot: "16:00" },
    ],
    "杭州": [
        { name: "西湖", description: "世界文化遗产，乘船游湖，欣赏断桥残雪和三潭印月", lat: 30.2590, lng: 120.1450, category: "自然", duration: "3小时", cost: 0, timeSlot: "09:00" },
        { name: "雷峰塔", description: "白蛇传传说之地，登塔俯瞰西湖全景", lat: 30.2290, lng: 120.1150, category: "历史", duration: "1小时", cost: 40, timeSlot: "08:00" },
        { name: "灵隐寺", description: "杭州最古老的佛教寺庙，飞来峰石刻造像精美绝伦", lat: 30.2590, lng: 120.1450, category: "历史", duration: "2小时", cost: 75, timeSlot: "10:30" },
        { name: "河坊街", description: "杭州历史文化街区，品尝定胜糕和龙井茶", lat: 30.2489, lng: 120.2050, category: "美食", duration: "1.5小时", cost: 0, timeSlot: "14:00" },
        { name: "龙井村", description: "西湖龙井茶的原产地，体验采茶和品茶", lat: 30.2290, lng: 120.1150, category: "自然", duration: "2小时", cost: 0, timeSlot: "15:30" },
        { name: "宋城", description: "大型宋文化主题公园，观看《宋城千古情》演出", lat: 30.2489, lng: 120.2050, category: "历史", duration: "3小时", cost: 320, timeSlot: "19:00" },
    ],
    "西安": [
        { name: "秦始皇兵马俑", description: "世界第八大奇迹，数千个真人大小的陶俑震撼人心", lat: 34.2610, lng: 108.9420, category: "历史", duration: "3小时", cost: 120, timeSlot: "08:00" },
        { name: "大雁塔", description: "唐代高僧玄奘译经之地，西安的标志性建筑", lat: 34.2650, lng: 108.9540, category: "历史", duration: "1.5小时", cost: 50, timeSlot: "11:00" },
        { name: "西安城墙", description: "中国保存最完整的古城墙，骑行一圈感受古都风貌", lat: 34.2750, lng: 108.9480, category: "摄影", duration: "2小时", cost: 54, timeSlot: "14:00" },
        { name: "回民街", description: "西安最著名的小吃街，品尝肉夹馍、凉皮和羊肉泡馍", lat: 34.2690, lng: 108.9580, category: "美食", duration: "2小时", cost: 0, timeSlot: "16:30" },
        { name: "钟楼", description: "西安市中心的地标建筑，登楼俯瞰古城四条大街", lat: 34.2583, lng: 108.9426, category: "夜景", duration: "1小时", cost: 30, timeSlot: "19:00" },
        { name: "大唐不夜城", description: "以盛唐文化为主题的步行街，灯光秀和表演精彩纷呈", lat: 34.2650, lng: 108.9540, category: "夜景", duration: "2小时", cost: 0, timeSlot: "20:00" },
    ],
    "曼谷": [
        { name: "大皇宫", description: "泰国最神圣的宫殿，玉佛寺内的翡翠佛是国宝", lat: 13.7563, lng: 100.5018, category: "历史", duration: "2小时", cost: 500, timeSlot: "09:00" },
        { name: "卧佛寺", description: "泰国最大的卧佛，全长46米，金碧辉煌", lat: 13.7280, lng: 100.5130, category: "历史", duration: "1小时", cost: 200, timeSlot: "11:00" },
        { name: "暹罗广场", description: "曼谷的时尚中心，汇集各大商场和网红餐厅", lat: 13.7440, lng: 100.5340, category: "购物", duration: "2小时", cost: 0, timeSlot: "14:00" },
        { name: "考山路", description: "全球背包客的天堂，夜市酒吧热闹非凡", lat: 13.7390, lng: 100.4930, category: "美食", duration: "2小时", cost: 0, timeSlot: "16:30" },
        { name: "乍都乍周末市场", description: "世界最大的周末市场，超过15000个摊位", lat: 13.7650, lng: 100.5380, category: "购物", duration: "3小时", cost: 0, timeSlot: "10:00" },
        { name: "摩天轮夜市", description: "湄南河畔的浪漫夜市，乘坐摩天轮欣赏夜景", lat: 13.7390, lng: 100.4930, category: "夜景", duration: "2小时", cost: 450, timeSlot: "19:00" },
    ],
    "新加坡": [
        { name: "滨海湾花园", description: "超级树丛和花穹，未来感十足的植物王国", lat: 1.2810, lng: 103.8590, category: "自然", duration: "2小时", cost: 28, timeSlot: "09:00" },
        { name: "鱼尾狮公园", description: "新加坡标志性雕塑，打卡必到之地", lat: 1.2830, lng: 103.8510, category: "摄影", duration: "0.5小时", cost: 0, timeSlot: "08:30" },
        { name: "乌节路", description: "新加坡的购物天堂，ION Orchard和义安城等大型商场林立", lat: 1.3040, lng: 103.8320, category: "购物", duration: "2小时", cost: 0, timeSlot: "14:00" },
        { name: "牛车水", description: "新加坡的唐人街，品尝海南鸡饭和肉骨茶", lat: 1.2860, lng: 103.8450, category: "美食", duration: "1.5小时", cost: 0, timeSlot: "11:30" },
        { name: "圣淘沙岛", description: "综合度假胜地，环球影城、S.E.A海洋馆和沙滩", lat: 1.2494, lng: 103.8302, category: "自然", duration: "4小时", cost: 82, timeSlot: "15:00" },
        { name: "克拉码头", description: "新加坡河畔的娱乐区，酒吧餐厅林立，夜景迷人", lat: 1.2860, lng: 103.8450, category: "夜景", duration: "2小时", cost: 0, timeSlot: "19:00" },
    ],
    "巴黎": [
        { name: "埃菲尔铁塔", description: "巴黎的标志，登塔俯瞰整个城市，夜晚灯光秀璀璨", lat: 48.8584, lng: 2.2945, category: "夜景", duration: "2小时", cost: 25, timeSlot: "09:00" },
        { name: "卢浮宫", description: "世界最大的博物馆，欣赏蒙娜丽莎和维纳斯雕像", lat: 48.8606, lng: 2.3376, category: "历史", duration: "3小时", cost: 17, timeSlot: "10:30" },
        { name: "巴黎圣母院", description: "哥特式建筑的代表作，雨果笔下的钟楼怪人", lat: 48.8556, lng: 2.3456, category: "历史", duration: "1小时", cost: 0, timeSlot: "14:00" },
        { name: "香榭丽舍大街", description: "世界最美的大道，从凯旋门到协和广场", lat: 48.8566, lng: 2.3522, category: "购物", duration: "2小时", cost: 0, timeSlot: "15:30" },
        { name: "蒙马特高地", description: "艺术家聚集地，圣心大教堂俯瞰巴黎全景", lat: 48.8738, lng: 2.2950, category: "咖啡馆", duration: "2小时", cost: 0, timeSlot: "19:00" },
        { name: "塞纳河游船", description: "乘坐游船欣赏塞纳河两岸的浪漫风光", lat: 48.8566, lng: 2.3522, category: "摄影", duration: "1小时", cost: 15, timeSlot: "20:00" },
    ],
    "伦敦": [
        { name: "大本钟", description: "伦敦的标志性钟楼，英国议会大厦的一部分", lat: 51.5007, lng: -0.1246, category: "摄影", duration: "0.5小时", cost: 0, timeSlot: "09:00" },
        { name: "伦敦眼", description: "泰晤士河畔的巨型摩天轮，俯瞰伦敦全景", lat: 51.5074, lng: -0.1278, category: "夜景", duration: "1小时", cost: 30, timeSlot: "10:00" },
        { name: "大英博物馆", description: "世界三大博物馆之一，收藏了来自全球的珍贵文物", lat: 51.5194, lng: -0.1270, category: "历史", duration: "3小时", cost: 0, timeSlot: "11:00" },
        { name: "伦敦塔桥", description: "泰晤士河上的标志性桥梁，参观桥塔内的展览", lat: 51.5081, lng: -0.0759, category: "历史", duration: "1.5小时", cost: 10, timeSlot: "14:30" },
        { name: "白金汉宫", description: "英国王室的官邸，观看皇家卫兵换岗仪式", lat: 51.5014, lng: -0.1419, category: "历史", duration: "1小时", cost: 0, timeSlot: "16:00" },
        { name: "考文特花园", description: "伦敦最具活力的街区，街头表演和特色市集", lat: 51.5115, lng: -0.1160, category: "美食", duration: "2小时", cost: 0, timeSlot: "19:00" },
    ],
    "纽约": [
        { name: "自由女神像", description: "美国的象征，乘船前往自由岛近距离参观", lat: 40.7061, lng: -74.0087, category: "历史", duration: "3小时", cost: 24, timeSlot: "09:00" },
        { name: "时代广场", description: "世界十字路口，霓虹灯牌和百老汇剧院区", lat: 40.7580, lng: -73.9855, category: "夜景", duration: "1小时", cost: 0, timeSlot: "10:30" },
        { name: "中央公园", description: "纽约的绿肺，骑马、划船、散步的好去处", lat: 40.7614, lng: -73.9776, category: "自然", duration: "2小时", cost: 0, timeSlot: "14:00" },
        { name: "帝国大厦", description: "纽约天际线的标志，86层观景台俯瞰全城", lat: 40.7484, lng: -73.9857, category: "夜景", duration: "1.5小时", cost: 44, timeSlot: "16:00" },
        { name: "第五大道", description: "全球最昂贵的购物街，奢侈品旗舰店云集", lat: 40.7527, lng: -73.9772, category: "购物", duration: "2小时", cost: 0, timeSlot: "19:00" },
        { name: "布鲁克林大桥", description: "纽约最古老的悬索桥，步行穿越欣赏曼哈顿天际线", lat: 40.7061, lng: -73.9969, category: "摄影", duration: "1小时", cost: 0, timeSlot: "08:00" },
    ],
    "香港": [
        { name: "维多利亚港", description: "世界三大天然良港之一，乘坐天星小轮欣赏两岸风光", lat: 22.3193, lng: 114.1694, category: "摄影", duration: "1小时", cost: 4, timeSlot: "09:00" },
        { name: "太平山顶", description: "香港最高点，乘坐山顶缆车俯瞰维港全景", lat: 22.2783, lng: 114.1747, category: "夜景", duration: "2小时", cost: 52, timeSlot: "10:30" },
        { name: "迪士尼乐园", description: "香港迪士尼，全球最小的迪士尼乐园但充满魅力", lat: 22.2840, lng: 114.1580, category: "摄影", duration: "6小时", cost: 639, timeSlot: "14:00" },
        { name: "尖沙咀海滨", description: "星光大道和钟楼，欣赏维港灯光秀幻彩咏香江", lat: 22.2960, lng: 114.1720, category: "夜景", duration: "1.5小时", cost: 0, timeSlot: "20:00" },
        { name: "铜锣湾", description: "香港最繁华的购物区，时代广场和崇光百货", lat: 22.3150, lng: 114.1850, category: "购物", duration: "2小时", cost: 0, timeSlot: "15:00" },
        { name: "兰桂坊", description: "香港著名的酒吧和夜生活区", lat: 22.3193, lng: 114.1694, category: "美食", duration: "2小时", cost: 0, timeSlot: "21:00" },
    ],
    "台北": [
        { name: "台北101", description: "台北地标，曾是世界最高建筑，89楼观景台俯瞰台北", lat: 25.0340, lng: 121.5645, category: "夜景", duration: "1.5小时", cost: 600, timeSlot: "09:00" },
        { name: "故宫博物院", description: "收藏了中华文物精华，翠玉白菜和肉形石是镇馆之宝", lat: 25.0750, lng: 121.5750, category: "历史", duration: "2.5小时", cost: 350, timeSlot: "10:30" },
        { name: "西门町", description: "台北最热闹的商圈，电影街和潮流文化聚集地", lat: 25.0420, lng: 121.5350, category: "购物", duration: "2小时", cost: 0, timeSlot: "14:00" },
        { name: "士林夜市", description: "台湾最大的夜市，品尝蚵仔煎、大肠包小肠和珍珠奶茶", lat: 25.0960, lng: 121.5250, category: "美食", duration: "2小时", cost: 0, timeSlot: "16:30" },
        { name: "信义商圈", description: "台北的曼哈顿，高端购物中心和精品店云集", lat: 25.0330, lng: 121.5654, category: "购物", duration: "2小时", cost: 0, timeSlot: "19:00" },
        { name: "九份老街", description: "宫崎骏《千与千寻》灵感来源地，山城夜景美不胜收", lat: 25.1100, lng: 121.8440, category: "美食", duration: "3小时", cost: 0, timeSlot: "15:00" },
    ],
};

export const RESTAURANTS: Record<string, { breakfast: string[]; lunch: string[]; dinner: string[] }> = {
    "东京": {
        breakfast: ["築地すし鮮（筑地市场）", "Doutor Coffee（连锁咖啡）", "吉野家（牛丼）"],
        lunch: ["一兰拉面（涩谷店）", "大戸屋（定食）", "築地玉寿司（回转寿司）"],
        dinner: ["叙々苑（烧肉）", "蟹道楽（银座店）", "居酒屋 鳥貴族（烤串）"],
    },
    "大阪": {
        breakfast: ["551蓬莱（肉包）", "コメダ珈琲店（早餐套餐）", "すき家（牛丼）"],
        lunch: ["たこ焼き 道頓堀くくる（章鱼烧）", "大阪王将（饺子）", "自由軒（咖喱饭）"],
        dinner: ["かに道楽（道顿堀店）", "串カツだるま（炸串）", "はり重（寿喜烧）"],
    },
    "首尔": {
        breakfast: ["Isaac Toast（三明治）", "Paris Baguette（面包咖啡）", "本粥（韩式粥）"],
        lunch: ["土俗村参鸡汤", "神仙雪浓汤", "明洞饺子（刀切面）"],
        dinner: ["姜虎东烤肉（明洞店）", "新村食堂（酱猪蹄）", "校村炸鸡（啤酒）"],
    },
    "北京": {
        breakfast: ["护国寺小吃（豆汁焦圈）", "庆丰包子铺", "姚记炒肝店"],
        lunch: ["全聚德烤鸭（前门店）", "东来顺涮羊肉", "海碗居炸酱面"],
        dinner: ["大董烤鸭（工体店）", "花家怡园（簋街店）", "海底捞火锅（三里屯）"],
    },
    "上海": {
        breakfast: ["小杨生煎", "大壶春生煎", "王家沙点心店"],
        lunch: ["南翔馒头店（豫园）", "鼎泰丰（新天地）", "老吉士（天平路）"],
        dinner: ["福1015（本帮菜）", "外滩三号Jean Georges", "海底捞（南京路）"],
    },
    "广州": {
        breakfast: ["点都德（早茶）", "陶陶居（早茶）", "广州酒家（早茶）"],
        lunch: ["银记肠粉", "陈添记鱼皮", "宝华面店（云吞面）"],
        dinner: ["炳胜品味（粤菜）", "惠食佳（啫啫煲）", "禄鼎记（酸菜鱼）"],
    },
    "成都": {
        breakfast: ["龙抄手（文殊院店）", "钟水饺（人民公园）", "赖汤圆（总府路）"],
        lunch: ["陈麻婆豆腐（骡马市）", "夫妻肺片（总店）", "洞子口张老二凉粉"],
        dinner: ["小龙坎火锅（春熙路）", "大龙燚火锅（九眼桥）", "蜀大侠火锅（宽窄巷子）"],
    },
    "杭州": {
        breakfast: ["知味观（小笼包）", "新丰小吃（虾肉馄饨）", "奎元馆（片儿川）"],
        lunch: ["楼外楼（西湖醋鱼）", "外婆家（龙井虾仁）", "绿茶餐厅（面包诱惑）"],
        dinner: ["张生记（老鸭煲）", "山外山菜馆（东坡肉）", "菊英面店（拌川）"],
    },
    "西安": {
        breakfast: ["老孙家羊肉泡馍", "贾三灌汤包子", "魏家凉皮"],
        lunch: ["同盛祥（泡馍）", "德发长（饺子宴）", "长安大牌档（葫芦鸡）"],
        dinner: ["西安饭庄（陕菜）", "醉长安（biangbiang面）", "回坊马峰（烤肉）"],
    },
    "曼谷": {
        breakfast: ["路邊攤（泰式奶茶+烤面包）", "After You Dessert Cafe", "7-11（泰式便当）"],
        lunch: ["建兴酒家（咖喱蟹）", "Nara Thai Cuisine（泰式炒面）", "Somtum Der（青木瓜沙拉）"],
        dinner: ["Jay Fai（米其林蟹肉蛋卷）", "Thip Samai（鬼门炒粉）", "Baan Khanitha（泰式料理）"],
    },
    "新加坡": {
        breakfast: ["亚坤咖椰吐司", "土司工坊（半熟蛋）", "南洋老咖啡（咖啡+面包）"],
        lunch: ["天天海南鸡饭（麦士威）", "松发肉骨茶", "328加东叻沙"],
        dinner: ["珍宝海鲜（辣椒螃蟹）", "文东记海南鸡饭", "黄亚细肉骨茶"],
    },
    "巴黎": {
        breakfast: ["Paul（法式面包）", "Angelina（热巧克力）", "Du Pain et des Idées（可颂）"],
        lunch: ["L'As du Fallafel（法拉费）", "Bouillon Chartier（法式简餐）", "Le Comptoir du Relais（法餐）"],
        dinner: ["Le Jules Verne（埃菲尔铁塔餐厅）", "Septime（米其林）", "Chez L'Ami Jean（巴斯克菜）"],
    },
    "伦敦": {
        breakfast: ["The Breakfast Club（英式早餐）", "Dishoom（孟买早餐）", "Pret A Manger（三明治）"],
        lunch: ["Burger & Lobster（龙虾汉堡）", "Flat Iron（牛排）", "Wahaca（墨西哥菜）"],
        dinner: ["Duck & Waffle（高空餐厅）", "Sketch（米其林）", "Borough Market（美食集市）"],
    },
    "纽约": {
        breakfast: ["Eggs Benedict（班尼迪克蛋）", "Russ & Daughters（烟熏三文鱼）", "Katz's Delicatessen（熏牛肉）"],
        lunch: ["Shake Shack（汉堡）", "Joe's Pizza（披萨）", "Xi'an Famous Foods（凉皮）"],
        dinner: ["Peter Luger（牛排）", "Carbone（意大利菜）", "Le Bernardin（米其林海鲜）"],
    },
    "香港": {
        breakfast: ["兰芳园（丝袜奶茶+菠萝油）", "澳洲牛奶公司（炖奶）", "添好运（酥皮叉烧包）"],
        lunch: ["镛记酒家（烧鹅）", "九记牛腩（清汤牛腩）", "一乐烧鹅（脆皮烧鹅）"],
        dinner: ["龙景轩（米其林粤菜）", "阿一海景饭店（鲍鱼）", "桥底辣蟹（避风塘炒蟹）"],
    },
    "台北": {
        breakfast: ["阜杭豆浆（厚烧饼）", "永和豆浆（豆浆油条）", "陈根找茶（法式吐司）"],
        lunch: ["鼎泰丰（小笼包）", "林东芳牛肉面", "永康牛肉面"],
        dinner: ["欣叶台菜（三杯鸡）", "RAW（米其林创意菜）", "饶河夜市（胡椒饼）"],
    },
};

export const HOTELS: Record<string, { budget: string[]; comfortable: string[]; luxury: string[]; hostel: string[] }> = {
    "东京": {
        budget: ["东横INN（浅草）", "APA酒店（新宿）", "Super Hotel（秋叶原）"],
        comfortable: ["三井花园饭店（银座）", "京王广场酒店（新宿）", "东京湾希尔顿"],
        luxury: ["东京半岛酒店", "东京皇宫酒店", "安缦东京"],
        hostel: ["Khaosan Tokyo（浅草）", "Nui. Hostel（藏前）", "Grids Hostel（秋叶原）"],
    },
    "大阪": {
        budget: ["东横INN（难波）", "APA酒店（心斋桥）", "Super Hotel（天王寺）"],
        comfortable: ["大阪瑞士南海酒店", "大阪日航酒店", "大阪万豪都酒店"],
        luxury: ["大阪瑞吉酒店", "大阪丽思卡尔顿", "大阪康莱德酒店"],
        hostel: ["Hostel Q（难波）", "J-Hoppers（天王寺）", "Drop Inn（心斋桥）"],
    },
    "首尔": {
        budget: ["东横INN（明洞）", "九树酒店（明洞）", "宜必思（首尔站）"],
        comfortable: ["首尔明洞相铁酒店", "GLAD酒店（汝矣岛）", "首尔花园酒店"],
        luxury: ["首尔朝鲜酒店", "首尔四季酒店", "首尔柏悦酒店"],
        hostel: ["Kimchee Guesthouse（明洞）", "Bunk Guesthouse（弘大）", "Zzzip Guesthouse（梨泰院）"],
    },
    "北京": {
        budget: ["如家酒店（前门）", "汉庭酒店（王府井）", "7天连锁（天安门）"],
        comfortable: ["北京诺富特和平宾馆", "北京金隅喜来登", "北京国际饭店"],
        luxury: ["北京王府井文华东方", "北京宝格丽酒店", "北京华尔道夫"],
        hostel: ["北京炮局工厂青年旅舍", "北京四合院青年旅舍", "北京鼓韵青年旅舍"],
    },
    "上海": {
        budget: ["如家酒店（南京路）", "汉庭酒店（外滩）", "全季酒店（人民广场）"],
        comfortable: ["上海大酒店（南京路）", "上海王宝和大酒店", "上海锦江饭店"],
        luxury: ["上海半岛酒店", "上海浦东丽思卡尔顿", "上海外滩华尔道夫"],
        hostel: ["上海蓝山国际青年旅舍", "上海老船长青年旅舍", "上海明堂青年旅舍"],
    },
    "广州": {
        budget: ["如家酒店（北京路）", "汉庭酒店（上下九）", "7天连锁（广州塔）"],
        comfortable: ["广州花园酒店", "广州中国大酒店", "广州东方宾馆"],
        luxury: ["广州四季酒店", "广州丽思卡尔顿", "广州文华东方酒店"],
        hostel: ["广州江畔国际青年旅舍", "广州东山口青年旅舍", "广州沙面青年旅舍"],
    },
    "成都": {
        budget: ["如家酒店（春熙路）", "汉庭酒店（宽窄巷子）", "全季酒店（锦里）"],
        comfortable: ["成都西藏饭店", "成都岷山饭店", "成都总府皇冠假日"],
        luxury: ["成都博舍", "成都华尔道夫", "成都瑞吉酒店"],
        hostel: ["成都四号工厂青年旅舍", "成都拖板鞋青年旅舍", "成都懒骨头青年旅舍"],
    },
    "杭州": {
        budget: ["如家酒店（西湖）", "汉庭酒店（武林广场）", "全季酒店（河坊街）"],
        comfortable: ["杭州黄龙饭店", "杭州望湖宾馆", "杭州维景国际酒店"],
        luxury: ["杭州西子湖四季酒店", "杭州安缦法云", "杭州悦榕庄"],
        hostel: ["杭州明堂青年旅舍", "杭州荷方青年旅舍", "杭州吴山驿青年旅舍"],
    },
    "西安": {
        budget: ["如家酒店（钟楼）", "汉庭酒店（大雁塔）", "全季酒店（回民街）"],
        comfortable: ["西安索菲特人民大厦", "西安皇冠假日酒店", "西安威斯汀酒店"],
        luxury: ["西安丽思卡尔顿", "西安W酒店", "西安凯悦酒店"],
        hostel: ["西安七贤国际青年旅舍", "西安湘子门青年旅舍", "西安汉唐驿青年旅舍"],
    },
    "曼谷": {
        budget: ["Nasa Bangkok（素万那普）", "Rikka Inn（考山路）", "Lub d（暹罗）"],
        comfortable: ["曼谷暹罗凯宾斯基", "曼谷悦榕庄", "曼谷千禧希尔顿"],
        luxury: ["曼谷半岛酒店", "曼谷文华东方", "曼谷四季酒店"],
        hostel: ["Bed Station Hostel（考山路）", "Here Hostel（暹罗）", "Pama's House（考山路）"],
    },
    "新加坡": {
        budget: ["Village Hotel Bugis", "Hotel Boss（劳明达）", "Fragrance Hotel（武吉士）"],
        comfortable: ["新加坡滨海湾宾乐雅", "新加坡国敦河景酒店", "新加坡史各士皇族酒店"],
        luxury: ["新加坡滨海湾金沙", "新加坡莱佛士酒店", "新加坡文华东方"],
        hostel: ["Hive Boutique Hostel", "Wink Hostel（牛车水）", "Adventure Hostel（小印度）"],
    },
    "巴黎": {
        budget: ["Ibis Paris（埃菲尔铁塔）", "Campanile（巴黎13区）", "B&B Hotel（蒙马特）"],
        comfortable: ["巴黎万豪酒店（香榭丽舍）", "巴黎洲际大酒店", "巴黎索菲特（凯旋门）"],
        luxury: ["巴黎丽兹酒店", "巴黎香格里拉", "巴黎半岛酒店"],
        hostel: ["Generator Hostel（巴黎）", "St Christopher's（巴黎）", "The People Hostel（巴黎）"],
    },
    "伦敦": {
        budget: ["Premier Inn（伦敦眼）", "Travelodge（考文特花园）", "Ibis London（泰晤士河）"],
        comfortable: ["伦敦希尔顿（海德公园）", "伦敦万豪（格罗夫纳广场）", "伦敦威斯敏斯特酒店"],
        luxury: ["伦敦丽兹酒店", "伦敦萨伏伊酒店", "伦敦多切斯特酒店"],
        hostel: ["Generator Hostel（伦敦）", "YHA London（圣潘克拉斯）", "Safestay（伦敦）"],
    },
    "纽约": {
        budget: ["Pod 51（中城东）", "Yotel（时代广场）", "The Jane Hotel（西村）"],
        comfortable: ["纽约希尔顿（中城）", "纽约万豪（时代广场）", "纽约凯悦（中央公园）"],
        luxury: ["纽约瑞吉酒店", "纽约半岛酒店", "纽约四季酒店"],
        hostel: ["HI NYC Hostel（上西区）", "Jazz on the Park（中央公园）", "NY Moore Hostel（布鲁克林）"],
    },
    "香港": {
        budget: ["香港红茶馆酒店", "香港金域假日酒店（尖沙咀）", "香港如心海景酒店"],
        comfortable: ["香港朗廷酒店（尖沙咀）", "香港帝京酒店（旺角）", "香港九龙酒店"],
        luxury: ["香港半岛酒店", "香港四季酒店", "香港丽思卡尔顿"],
        hostel: ["Hop Inn（尖沙咀）", "Urban Pack Hostel（旺角）", "Yesinn Hostel（铜锣湾）"],
    },
    "台北": {
        budget: ["台北西门町意舍", "台北日记商旅（台北车站）", "台北德立庄酒店"],
        comfortable: ["台北君品酒店（台北车站）", "台北寒舍艾丽酒店", "台北晶华酒店"],
        luxury: ["台北文华东方酒店", "台北W酒店", "台北君悦酒店"],
        hostel: ["台北夹脚拖青年旅舍", "台北橙舍青年旅舍", "台北西门窝青年旅舍"],
    },
};

export const TRAVEL_TIPS: Record<string, string[]> = {
    "东京": [
        "购买Suica或Pasmo交通卡，方便乘坐地铁和公交",
        "东京地铁有日文和英文报站，提前下载Google Maps导航",
        "餐厅一般有午餐套餐（Lunch Set），比晚餐便宜很多",
        "涩谷十字路口最佳拍摄点在星巴克二楼",
        "浅草寺抽签如果是凶签，系在寺内的架子上不要带走",
    ],
    "大阪": [
        "购买大阪周游卡可免费进入多个景点",
        "道顿堀的蟹道乐需要提前预约",
        "环球影城建议购买快速通行券",
        "黑门市场下午去海鲜更便宜",
        "大阪的章鱼烧和东京口味不同，值得一试",
    ],
    "首尔": [
        "购买T-money交通卡，地铁和公交通用",
        "景福宫穿韩服可免费入场",
        "明洞换钱所汇率比银行好",
        "弘大周末有自由市场，很多独立设计师作品",
        "韩国餐厅基本都提供免费小菜",
    ],
    "北京": [
        "故宫门票需提前在官网预约",
        "北京地铁用亿通行APP扫码乘车",
        "长城建议早上去，避开人流高峰",
        "烤鸭推荐提前预约，全聚德和大董都需要排队",
        "胡同游推荐骑共享单车，方便又环保",
    ],
    "上海": [
        "上海地铁用Metro大都会APP扫码乘车",
        "外滩夜景最佳观赏时间在晚上7-9点",
        "迪士尼建议下载官方APP抢快速通行证",
        "豫园和城隍庙周末人很多，建议工作日去",
        "上海博物馆免费但需预约",
    ],
    "广州": [
        "广州地铁用羊城通或乘车码",
        "早茶一般从早上7点到下午2点",
        "广州塔摩天轮需要额外购票",
        "长隆建议买两日票更划算",
        "上下九和北京路都是步行街，适合逛吃",
    ],
    "成都": [
        "大熊猫基地建议早上8点前到，熊猫最活跃",
        "火锅店一般下午5点开始营业",
        "宽窄巷子和锦里晚上去更有氛围",
        "成都地铁用天府通APP",
        "看川剧变脸推荐去蜀风雅韵",
    ],
    "杭州": [
        "西湖免费开放，但游船需要购票",
        "灵隐寺建议早上去，人少清净",
        "龙井茶不要在景区买，去龙井村更正宗",
        "杭州地铁用杭州通或支付宝乘车码",
        "宋城千古情演出非常精彩，值得一看",
    ],
    "西安": [
        "兵马俑距离市区较远，建议预留半天时间",
        "西安城墙骑行一圈约2小时",
        "回民街晚上最热闹，但价格偏贵",
        "大雁塔北广场有音乐喷泉表演",
        "西安地铁用西安电子乘车码",
    ],
    "曼谷": [
        "大皇宫参观需穿过膝长裤/长裙",
        "曼谷堵车严重，建议坐BTS或MRT",
        "路边摊的泰式奶茶和芒果糯米饭必吃",
        "周末市场只有周六日开放",
        "摩天轮夜市在湄南河边，夜景很美",
    ],
    "新加坡": [
        "新加坡地铁用EZ-Link卡",
        "室内公共场所禁止吃口香糖",
        "滨海湾花园灯光秀每晚7:45和8:45",
        "圣淘沙岛可以坐缆车或捷运到达",
        "新加坡的海南鸡饭和肉骨茶是必吃美食",
    ],
    "巴黎": [
        "巴黎地铁票可以买10次票更划算",
        "卢浮宫每月第一个周日免费",
        "埃菲尔铁塔晚上整点有灯光闪烁",
        "巴黎餐厅一般包含服务费，小费不是必须",
        "蒙马特高地的圣心大教堂免费参观",
    ],
    "伦敦": [
        "伦敦地铁用Oyster卡最方便",
        "大英博物馆免费但建议提前预约",
        "伦敦眼建议提前网上购票避免排队",
        "白金汉宫卫兵换岗每天11:00（夏季）",
        "考文特花园的街头表演非常精彩",
    ],
    "纽约": [
        "纽约地铁用MetroCard或OMNY支付",
        "自由女神像需要提前预约船票",
        "时代广场晚上去更有氛围",
        "中央公园可以租自行车骑行",
        "百老汇演出可以在TKTS买折扣票",
    ],
    "香港": [
        "八达通卡适用于所有公共交通",
        "太平山顶缆车建议买往返票",
        "迪士尼建议工作日去人少",
        "尖沙咀海滨每晚8点有灯光秀",
        "茶餐厅的丝袜奶茶和菠萝油是经典",
    ],
    "台北": [
        "台北捷运用悠游卡",
        "台北101观景台建议傍晚去，看日落和夜景",
        "士林夜市是台湾最大的夜市",
        "九份老街建议下午去，看山城夜景",
        "故宫博物院每周六晚上免费开放",
    ],
};
